### ISSUE TITLE
Support for exception thrown by Java methods

### ISSUE THREAD

**Issue by venator85** [csense-oss/idea-kotlin-checked-exceptions#1]
Hi, it would be incredibly useful if you could extend this plugin to support also exception thrown by Java methods, e.g.

    public class Foo {
        public void foo() throws Exception {
        }
    }

    object Bar {
        fun bar() {
            Foo().foo()   // << checked exception not catched, warning should appear
        }
    }

This would be very useful, for example, on Android, that often uses checked exceptions in the system API (that cannot be changed of course), that are very easy to forget catching, resulting in a crash of the app.
Thanks!

**Comment by Tvede-dk** [comment]
So in the latest version (0.9.10) it should be working just fine. 
![image](https://user-images.githubusercontent.com/5425815/72265525-f1af4080-361c-11ea-89aa-d7245e6f2cb6.png)
If it is still causing issues, then feel free to elaborate on it, as I will gladly look into it :) Thanks for reporting !
