### ISSUE TITLE
Fatal Error when running the plugin

### ISSUE THREAD

**Issue by cralcubo** [csense-oss/idea-kotlin-checked-exceptions#12]
IDE: IntelliJ IDEA 2021.3.3 (Community Edition)

First of all, thanks for thinking and implementing this plugin!

I installed the plugin (only the **idea-kotlin-checked-exceptions-1.2.0.jar**) and restarted the IDE and when the IDE was up, the following **Fatal Error** was reported:

> java.lang.NoClassDefFoundError: csense/idea/base/bll/kotlin/KtCallExpressionKt
> 	at csense.idea.kotlin.checked.exceptions.cache.SharedMethodThrowingCache.resolveThrows(SharedMethodThrowingCache.kt:16)
> 	at csense.idea.kotlin.checked.exceptions.cache.SharedMethodThrowingCache.throwsTypes(SharedMethodThrowingCache.kt:11)
> 	at csense.idea.kotlin.checked.exceptions.lineMarkers.CheckedExceptionLineMarkerProvider.collectNavigationMarkers(CheckedExceptionLineMarkerProvider.kt:33)
> 	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:31)
> 	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:23)
> 	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:195)
> 	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
> 	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:115)
> 	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:85)
> 	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
> 	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> Caused by: java.lang.ClassNotFoundException: csense.idea.base.bll.kotlin.KtCallExpressionKt PluginClassLoader(plugin=PluginDescriptor(name=Csense - Kotlin Checked Exceptions, id=csense-idea.kotlin-checked-exceptions, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2021.3/plugins/idea-kotlin-checked-exceptions-1.2.0.jar, version=1.2.0, package=null, isBundled=false), packagePrefix=null, instanceId=102, state=active)
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 29 more
> 

Hope you find time to fix this issue, or maybe am I doing something wrong?

Looking forward to hearing from you!

**Comment by Tvede-dk** [comment]
Hi, please test when version 2.0 is released (it has been sent to jetbrains as of writing). if it persists then ill be happy to help :)
