### ISSUE TITLE
Exception warnings not shown if called function has only @throws in docs

### ISSUE THREAD

**Issue by urosjarc** [csense-oss/idea-kotlin-checked-exceptions#13]
Plugin does not provide warnings on folowing case...

```
/**
 * @throws RuntimeException
 */
fun test(){
   println("Hello World")
}



fun main() {
    test()
}
```

**Comment by Tvede-dk** [comment]
Hi, 
You are absolutely right, that was a decision way back to limit the scope in the first version(s). 
It might make it into version 2.0.0 :)

**Comment by Tvede-dk** [comment]
This  should be working in 2.0
