### ISSUE TITLE
Exception hierarchy is not treated properly

### ISSUE THREAD

**Issue by daniel-jasinski** [csense-oss/idea-kotlin-checked-exceptions#18]
When a method body throws a derived exception type and the method declares base class type the plugin issues a warning.

**Comment by Tvede-dk** [comment]
@daniel-jasinski Can you verify that it is this case? 
![image](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/5425815/439a01c4-a357-49da-9f50-328eb7b893f9)

Or is it that you do not want to annotate the overriden function? 
Thanks :)

**Comment by daniel-jasinski** [comment]
I can confirm, this is an example:

![image](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/4387323/ba34affe-4275-4f3e-89d6-68fc3c3655ee)

**Comment by Tvede-dk** [comment]
Fixed in 2.1.1
