### ISSUE TITLE
Mark function as ignored / callthrough not working

### ISSUE THREAD

**Issue by Doomsdayrs** [csense-oss/idea-kotlin-checked-exceptions#21]
[Screencast from 2023-12-02 13-58-48.webm](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/38189170/42689bc5-ea36-483c-a195-1be0e2966a59)

**Comment by Tvede-dk** [comment]
Is fixed in the next version (at least the file related issues) .
