### ISSUE TITLE
The highlight cannot be turned off using try + catch (exception) and @Throw(Exception::class). You must use @Throw(Throwable::class) to turn it off

### ISSUE THREAD

**Issue by RiniceSiberia** [csense-oss/idea-kotlin-checked-exceptions#25]
![QQ截图20240306095135](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/38497360/d5b7ea15-1d86-4d58-a623-0d4be37113f2)

**Comment by Tvede-dk** [comment]
Fixed in 2.1.1

**Comment by RiniceSiberia** [comment]
it hasn't been fixed
![QQ截图20240327103741](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/38497360/8be6e817-e768-432f-b59e-c85af51706f1)
![QQ截图20240327103900](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/38497360/2daa4566-f2e2-468c-96d7-18074494a7fb)

**Comment by Tvede-dk** [comment]
Hmm
There are really 2 cases
1) (the fixed one) is where the the caught exception was a kotlin exception (with type alias)
2) (this is not fixed) is where the caught exception is a java exception. So if both are kotlin exceptions then that is another issue. eg: 
![image](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/5425815/ed17072f-9ada-408b-ba9d-56e16da5c54f)

However a simple test yields this
![image](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/5425815/90bcae90-029d-4395-a8ca-7829905d24c8)

But adding the also is what triggers this. 
![image](https://github.com/csense-oss/idea-kotlin-checked-exceptions/assets/5425815/12edf23c-7608-426c-96e7-cb72948ec9c9)

Thus this is actually a new issue :) 
https://github.com/csense-oss/idea-kotlin-checked-exceptions/issues/26
