### ISSUE TITLE
CSense detects `Throws` annotation only if lambda provides `callsInPlace` contract

### ISSUE THREAD

**Issue by and-marsh** [csense-oss/idea-kotlin-checked-exceptions#27]
Hey, good job with the plugin!

I have noticed the following behavior, and I was wondering if it's intended or forced by some internal limitations. Here is the snippet where I call the function that throws inside of a lambda function. In such a scenario, CSense doesn't detect if the exception is handled or not.

<img width="1089" alt="image" src="https://github.com/csense-oss/csense-oss-idea-kotlin-shared-test/assets/39465943/d83d5b88-2702-45fd-a72a-7304cbd1612c">

And the warning disappears if the lambda function provides an "InPlace" contract:

<img width="913" alt="image" src="https://github.com/csense-oss/csense-oss-idea-kotlin-shared-test/assets/39465943/2ad8778a-71cc-40f8-b439-3cf64f286140">

This might not be related, but I suppose it's ok to file it here. Even with the "InPlace" contract, there is no suggestion to add an annotation to the function, only wrap it with try/catch:

<img width="913" alt="image" src="https://github.com/csense-oss/csense-oss-idea-kotlin-shared-test/assets/39465943/66845b98-a306-4a71-84c4-5c189e772d2d">

Thanks in advance for looking into it!

**Comment by Tvede-dk** [comment]
Hi, 
And thanks for reporting :) 
The first thing is that the plugin does not do any kind of deep analysis, that would kill performance. Thus it needs to know from each method how to treat it. 

There are 2 (3) ways the plugin knows that a given method rethrows the exception. contract with calls in place is one of those. Another is an entry in the  ".callthough.throws" file. (unfortunatly that seems to be missing from the quickfix actions as well). 3 is a feature I'm working on, where you can apply an annotation (but this is quite complicated and takes some time) 

The format of the ".callthough.throws" and ".ignore.throws" files are the same, so it should be pretty simple to at least manually fix it for now, until a fix is provided.

and finally, yes, that is a bug, it should suggest both to add the entry to  ".callthough.throws" and to annotate the method.

**Comment by and-marsh** [comment]
Thanks for the response!

Great to have some options for workaround, but looking forward to the more refined solution as well!

**Comment by Tvede-dk** [comment]
It should be fixed in the comming 2.1.2 :) 
(should be out in about 2 days)
