### ISSUE TITLE
"Hightlight (via gutter) the throws expression" cannot be disabled

### ISSUE THREAD

**Issue by stapel** [csense-oss/idea-kotlin-checked-exceptions#3]
The option `Hightlight (via gutter) the throws expression` cannot be deactivated. You can uncheck the checkbox, but neither apply (which would not light up) nor OK afterwards save the setting.

**Comment by Tvede-dk** [comment]
Hi, 
You are absolutely correct, and it will be fixed in the next version :)

**Comment by Tvede-dk** [comment]
Should be fixed in 1.0
