### ISSUE TITLE
Unable to disable highlights of runtime exceptions

### ISSUE THREAD

**Issue by aesy** [csense-oss/idea-kotlin-checked-exceptions#5]
Hi, thanks for a great plugin! 

I have some issues with the `Highlight runtime exceptions as checked exceptions` setting. I have disabled it, but exceptions such as `IllegalStateException` are still being highlighted. Is this a known issue?

**Comment by Tvede-dk** [comment]
Hi, 
You are welcome :) 

What package name is the ```IllegalStateException``` from ? (a quick check is to close the file and reopen it, in case the inspection Daemon in IDEA did not restart) 
And what IDEA version are you using ?
What plugin version are you using ?

from what I can see in my installation(s) it seems to work fine though, so I'm quite interested if this is something related to different IDEA versions :)

**Comment by aesy** [comment]
I was referring to `java.lang.IllegalStateException`, but it seems any built-in java exception will be marked. If I implement and throw my own runtime exception, it isn't marked as a warning!

I'm using IntelliJ IDEA 2020.2 (Ultimate Edition) Build IU-202.6397.94 and version 1.0.1 of the plugin. I've tried both on Windows 10 and Arch Linux with the same result. I've also tried reopening the file and restarting the IDE. 

I can help you debug if there is any particular piece of code you want checked.

**Comment by Tvede-dk** [comment]
Well that even complicates it more; as of now I have tried to reproduce it via a number of ways, without success; 
Do you have any simple / short example of what you do exactly ?  (is it an MPP project or regular JVM ? or android ?)

I have created a newer version that might address it, although I would be surprised if that actually solved it. 
(attached below, will you try it out and see if it changes anything ? ) 
[idea-kotlin-checked-exceptions-1.0.2.zip](https://github.com/csense-oss/idea-kotlin-checked-exceptions/files/5075894/idea-kotlin-checked-exceptions-1.0.2.zip)

**Comment by aesy** [comment]
It's a regular JVM project. I've created a minimal project that reproduces the issue (on my end anyway). It's just a simple gradle project with a main file that may throw either a checked or a runtime exception. Both exceptions are highlighted for me in 1.0.1 and the 1.0.2 version you uploaded. [minimal-project.zip](https://github.com/csense-oss/idea-kotlin-checked-exceptions/files/5076839/minimal-project.zip). Any idea where we can go from here?

**Comment by Tvede-dk** [comment]
Ahh now I see; the problem is that I understood it as "catching" or exceptions being thrown by method invocation (thus the inspection) but this is when you are throwing a Runtime Exception. 
And of cause, disabling Runtime Exceptions should also disable both the highlighting and the gutter.

It would be really easy to spot as marking a function throwing RuntimeException and then using that would either highlight it or not 
```kotlin
@Throws(RuntimeException::class)
fun a(){
 
}
fun useA(){
   a()
}
```

**Comment by aesy** [comment]
I'm not sure I follow. In your example, with the setting on, what should be highlighted? `a()`?

**Comment by Tvede-dk** [comment]
Yes.
but that is a whole different thing from the issue you are describing with the example :) 
So I guess that if you turn off / on the setting , ```a()``` will get highlighted accordingly.

**Comment by Tvede-dk** [comment]
For good measures sake; this should fix the issue(s) 
(and a lot other, but that is not the purpose as of now)
can you verify if it indeed solves all the issues you have been facing ? 
[idea-kotlin-checked-exceptions-1.1.0.zip](https://github.com/csense-oss/idea-kotlin-checked-exceptions/files/5077370/idea-kotlin-checked-exceptions-1.1.0.zip)
